name: "Основы Nim: Знакомство с языком"

on: [push, workflow_dispatch]

jobs:
  task_1:
    runs-on: ubuntu-latest
    steps:
    - name: "Установка зависимостей"
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 2.0.8
    - uses: actions/checkout@v4
    - name: "Сборка main_1"
      run: nim c main_1
    - name: "Запуск main_1"
      run: ./main_1

  task_2:
    runs-on: ubuntu-latest
    steps:
    - name: "Установка зависимостей"
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 2.0.8
    - uses: actions/checkout@v4
    - name: "Сборка main_2"
      run: nim c main_2
    - name: "Запуск main_2"
      run: ./main_2

  task_3:
    runs-on: ubuntu-latest
    steps:
    - name: "Установка зависимостей"
      uses: jiro4989/setup-nim-action@v1
      with:
        nim-version: 2.0.8
    - uses: actions/checkout@v4
    - name: "Сборка main_3"
      run: nim c main_3
    - name: "Запуск main_3"
      run: ./main_3